# Generated by Django 6.0.3 on 2026-03-16 12:57

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ('google_id', models.CharField(max_length=255, unique=True)),
                ('verified', models.BooleanField(default=False)),
            ],
        ),
    ]
