# Copyright 2026 Giles Strong
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
Django settings for app project.

Generated by 'django-admin startproject' using Django 5.2.10.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import sys
from pathlib import Path

import logfire
from celery.schedules import crontab
from kombu import Exchange, Queue

from app.app_settings import APP_SETTINGS

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = APP_SETTINGS.SECRET_KEY

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = APP_SETTINGS.DEBUG

ALLOWED_HOSTS: list[str] = APP_SETTINGS.ALLOWED_HOSTS
IS_DEPLOY_ENV = APP_SETTINGS.ENVIRONMENT in ("staging", "production")

if IS_DEPLOY_ENV:
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    USE_X_FORWARDED_HOST = True
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
else:
    SECURE_PROXY_SSL_HEADER = None
    USE_X_FORWARDED_HOST = False
    SECURE_SSL_REDIRECT = False
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False

SECURE_HSTS_SECONDS = (
    APP_SETTINGS.SECURE_HSTS_SECONDS
    if APP_SETTINGS.SECURE_HSTS_SECONDS is not None
    else (31536000 if IS_DEPLOY_ENV else 0)
)
SECURE_HSTS_INCLUDE_SUBDOMAINS = (
    APP_SETTINGS.SECURE_HSTS_INCLUDE_SUBDOMAINS
    if APP_SETTINGS.SECURE_HSTS_INCLUDE_SUBDOMAINS is not None
    else IS_DEPLOY_ENV
)
SECURE_HSTS_PRELOAD = APP_SETTINGS.SECURE_HSTS_PRELOAD if APP_SETTINGS.SECURE_HSTS_PRELOAD is not None else False

SESSION_COOKIE_HTTPONLY = APP_SETTINGS.SESSION_COOKIE_HTTPONLY
SESSION_COOKIE_SAMESITE = APP_SETTINGS.SESSION_COOKIE_SAMESITE
CSRF_COOKIE_HTTPONLY = APP_SETTINGS.CSRF_COOKIE_HTTPONLY
CSRF_COOKIE_SAMESITE = APP_SETTINGS.CSRF_COOKIE_SAMESITE
SECURE_CONTENT_TYPE_NOSNIFF = APP_SETTINGS.SECURE_CONTENT_TYPE_NOSNIFF
SECURE_REFERRER_POLICY = APP_SETTINGS.SECURE_REFERRER_POLICY
X_FRAME_OPTIONS = APP_SETTINGS.X_FRAME_OPTIONS
CSRF_TRUSTED_ORIGINS = APP_SETTINGS.CSRF_TRUSTED_ORIGINS

# Disable runtime type checks during testing to allow for mocking
TESTING = "pytest" in sys.modules or "test" in sys.argv
DISABLE_RUNTIME_TYPECHECKS = TESTING

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'appuser',
    "appauth",
    "appcore",
    "appsearch",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'appauth.middleware.CookieAuthCSRFMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'app.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'app.wsgi.application'
ASGI_APPLICATION = "app.asgi.application"

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases


DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": APP_SETTINGS.POSTGRES_DB,
        "USER": APP_SETTINGS.POSTGRES_USER,
        "PASSWORD": APP_SETTINGS.POSTGRES_PASSWORD,
        "HOST": APP_SETTINGS.POSTGRES_HOST,
        "PORT": APP_SETTINGS.POSTGRES_PORT,
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
MEDIA_URL = '/media/'

if APP_SETTINGS.ENVIRONMENT in ("staging", "production"):
    STATIC_ROOT = Path("/app/staticfiles")
    MEDIA_ROOT = Path("/app/media")
else:
    STATIC_ROOT = BASE_DIR / 'staticfiles'
    MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


CELERY_BROKER_URL = APP_SETTINGS.CELERY_BROKER_URL
CELERY_RESULT_BACKEND = APP_SETTINGS.CELERY_RESULT_BACKEND

CELERY_TASK_DEFAULT_QUEUE = APP_SETTINGS.CELERY_TASK_DEFAULT_QUEUE
CELERY_TASK_DEFAULT_EXCHANGE = APP_SETTINGS.CELERY_TASK_DEFAULT_EXCHANGE
CELERY_TASK_DEFAULT_ROUTING_KEY = APP_SETTINGS.CELERY_TASK_DEFAULT_ROUTING_KEY
CELERY_TASK_CREATE_MISSING_QUEUES = APP_SETTINGS.CELERY_TASK_CREATE_MISSING_QUEUES

CELERY_TASK_QUEUES = (
    Queue("default", Exchange("default"), routing_key="default"),
    Queue("llm", Exchange("llm"), routing_key="llm"),
)

if TESTING:
    CELERY_TASK_ALWAYS_EAGER = True
    CELERY_TASK_EAGER_PROPAGATES = True


CELERY_BEAT_SCHEDULE = {
    "daily-job-attempt": {
        "task": "appai.tasks.daily_theme.make_daily_theme",
        "schedule": crontab(minute="*/30"),  # every 30 minutes, but only completes once a day due to early exit
    },
    "cleanup-old-deck-build-tasks": {
        "task": "appai.tasks.cleanup.cleanup_old_deck_build_tasks",
        "schedule": crontab(minute="*/30"),  # every 30 minutes
    },
}

if not TESTING:
    logfire.configure(environment=APP_SETTINGS.LOGFIRE_ENVIRONMENT, token=APP_SETTINGS.LOGFIRE_TOKEN)
    logfire.instrument_pydantic_ai()

# Set API keys as environment variables for any libraries that expect them there, e.g. 
# os.environ["GOOGLE_API_KEY"] = APP_SETTINGS.GOOGLE_API_KEY
# os.environ["DEEPSEEK_API_KEY"] = APP_SETTINGS.DEEPSEEK_API_KEY
